name: 'Test image build'
on:
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      - uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          cd docker-only
          ./run.sh

      - name: Diagnostics
        run: |
          node --version
          docker buildx version
          docker version
          find /tmp/vsch-runner/container-features -type f -exec sha256sum {} \;
          mount
